First eslint pass

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,10 +1,24 @@
 #!/bin/bash
 
+npm install --no-save @typescript-eslint/eslint-plugin eslint-plugin-editorconfig
+
 git diff --cached --name-status | while read st file; do
   if [ "$st" == 'D' ]; then continue; fi
   if ! [[ "${file:(-3)}" == ".js" ]]; then continue; fi
   echo -en "[    ] Linting ${file}"
-  npm install --no-save eslint-plugin-editorconfig
+  results=$(npx -y eslint --config eslint.config.js "${file}" 2>&1)
+  if [ "$?" -ne "0" ]; then
+    echo -en "\r[fail]\n"
+    printf "%s\n" "$results"
+    exit 1
+  fi
+    echo -en "\r[pass]\n"
+done
+
+git diff --cached --name-status | while read st file; do
+  if [ "$st" == 'D' ]; then continue; fi
+  if ! [[ "${file:(-3)}" == ".ts" ]]; then continue; fi
+  echo -en "[    ] Linting ${file}"
   results=$(npx -y eslint --config eslint.config.js "${file}" 2>&1)
   if [ "$?" -ne "0" ]; then
     echo -en "\r[fail]\n"
